export const DEFAULT_ROLES: Record<string, string[]> = {
  'role:user:student': [
    'action:user:read:me',
    'action:user:update:me',
    'action:course:list',
    'action:course:read',
    'action:lesson:list',
    'action:lesson:read',
    'action:user_progress:read',
    'action:user_progress:create',
    'action:user_progress:update',
  ],
  'role:user:operator': [
    'action:user:read:me',
    'action:user:update:me',
    'action:course:list',
    'action:course:read',
    'action:course:create',
    'action:course:update',
    'action:course:delete',
    'action:lesson:list',
    'action:lesson:read',
    'action:lesson:create',
    'action:lesson:update',
    'action:lesson:delete',
    'action:user_progress:read',
    'action:user_progress:create',
    'action:user_progress:update',
    'action:admin:course:create',
    'action:admin:course:update',
    'action:admin:course:delete',
    'action:admin:lesson:create',
    'action:admin:lesson:update',
    'action:admin:lesson:delete',
    'action:admin:user:list',
    'action:admin:user:read',
    'action:admin:user:update',
  ],
  'role:user:admin': [
    // Admin role receives all existing permissions during the load process implicitly,
    // or we can define them explicitly if we don't want a wildcard.
    // For now, the load-iam-data script will give all permissions found in the DB to admin.
  ],
};
